version: '3'
services:
  nginx:
    image: nginx:1.19.1
    container_name: nginx
    ports:
      - 8000:8080
    depends_on:
      - php
      - db
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html

  php:
    build: ./docker/php
    container_name: php
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
      - ./docker/php/log/:/var/log/php/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.0
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    depends_on:
      - db
    ports:
      - 8086:80

  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/log/:/var/log/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
